import json

JSON_PATH = "/home/nfm/Desktop/rhome/nfm/ViT-Prisma/mynotebooks/groups_output_combined_new.json"

# class -> list of groups (based on defining characteristics of each scene)
mapping = {
    "abbey": ["Architecture & Buildings", "Religious & Spiritual", "Historical & Antique"],
    "airplane_cabin": ["Transportation & Vehicles"],
    "airport_terminal": ["Architecture & Buildings", "Transportation & Vehicles", "Urban & City Scenes"],
    "alley": ["Urban & City Scenes"],
    "amphitheater": ["Architecture & Buildings", "Historical & Antique"],
    "amusement_arcade": ["Toys, Games & Recreation"],
    "amusement_park": ["Toys, Games & Recreation", "Outdoor & Camping"],
    "anechoic_chamber": ["Technology & Electronics", "Medical & Scientific"],
    "apartment_building_outdoor": ["Architecture & Buildings", "Urban & City Scenes"],
    "apse_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "aquarium": ["Marine & Aquatic Life", "Water & Aquatic"],
    "aqueduct": ["Architecture & Buildings", "Historical & Antique", "Structures & Barriers", "Water & Aquatic"],
    "arch": ["Architecture & Buildings", "Structures & Barriers"],
    "archive": ["Architecture & Buildings", "Office & Stationery"],
    "arrival_gate_outdoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "art_gallery": ["Architecture & Buildings", "Artistic Styles & Movements"],
    "art_school": ["Architecture & Buildings", "Artistic Styles & Movements"],
    "art_studio": ["Artistic Styles & Movements"],
    "assembly_line": ["Industrial & Manufacturing"],
    "athletic_field_outdoor": ["Sports & Athletics"],
    "atrium_public": ["Architecture & Buildings"],
    "attic": ["Household Objects & Furniture", "Architecture & Buildings"],
    "auditorium": ["Architecture & Buildings", "Music, Dance & Performance"],
    "auto_factory": ["Industrial & Manufacturing", "Transportation & Vehicles"],
    "badlands": ["Natural Landscapes", "Natural Landforms & Geology"],
    "badminton_court_indoor": ["Sports & Athletics"],
    "baggage_claim": ["Transportation & Vehicles", "Architecture & Buildings"],
    "bakery_shop": ["Food & Cuisine", "Markets & Commerce"],
    "balcony_exterior": ["Architecture & Buildings"],
    "balcony_interior": ["Architecture & Buildings", "Household Objects & Furniture"],
    "ball_pit": ["Toys, Games & Recreation"],
    "ballroom": ["Architecture & Buildings", "Music, Dance & Performance"],
    "bamboo_forest": ["Trees & Forests", "Plants & Botanical"],
    "banquet_hall": ["Architecture & Buildings", "Food & Cuisine"],
    "bar": ["Food & Cuisine"],
    "barn": ["Architecture & Buildings", "Outdoor & Camping"],
    "barndoor": ["Structures & Barriers", "Architecture & Buildings"],
    "baseball_field": ["Sports & Athletics"],
    "basement": ["Architecture & Buildings", "Household Objects & Furniture"],
    "basilica": ["Architecture & Buildings", "Religious & Spiritual", "Historical & Antique"],
    "basketball_court_outdoor": ["Sports & Athletics"],
    "bathroom": ["Household Objects & Furniture"],
    "batters_box": ["Sports & Athletics"],
    "bayou": ["Water & Aquatic", "Natural Landscapes"],
    "bazaar_indoor": ["Markets & Commerce", "Cultural & Traditional"],
    "bazaar_outdoor": ["Markets & Commerce", "Cultural & Traditional"],
    "beach": ["Natural Landscapes", "Water & Aquatic"],
    "beauty_salon": ["Markets & Commerce"],
    "bedroom": ["Household Objects & Furniture"],
    "berth": ["Transportation & Vehicles"],
    "biology_laboratory": ["Medical & Scientific"],
    "bistro_indoor": ["Food & Cuisine"],
    "boardwalk": ["Water & Aquatic", "Structures & Barriers"],
    "boat_deck": ["Transportation & Vehicles", "Water & Aquatic"],
    "boathouse": ["Architecture & Buildings", "Water & Aquatic"],
    "bookstore": ["Markets & Commerce", "Letters, Text & Writing"],
    "booth_indoor": ["Architecture & Buildings"],
    "botanical_garden": ["Plants & Botanical", "Natural Landscapes"],
    "bow_window_indoor": ["Architecture & Buildings", "Household Objects & Furniture"],
    "bow_window_outdoor": ["Architecture & Buildings"],
    "bowling_alley": ["Sports & Athletics", "Toys, Games & Recreation"],
    "boxing_ring": ["Sports & Athletics"],
    "brewery_indoor": ["Industrial & Manufacturing", "Food & Cuisine"],
    "bridge": ["Architecture & Buildings", "Structures & Barriers"],
    "building_facade": ["Architecture & Buildings"],
    "bullring": ["Sports & Athletics", "Cultural & Traditional"],
    "burial_chamber": ["Religious & Spiritual", "Historical & Antique"],
    "bus_interior": ["Transportation & Vehicles"],
    "butchers_shop": ["Markets & Commerce", "Food & Cuisine"],
    "butte": ["Natural Landforms & Geology", "Natural Landscapes"],
    "cabin_outdoor": ["Architecture & Buildings", "Outdoor & Camping"],
    "cafeteria": ["Food & Cuisine"],
    "campsite": ["Outdoor & Camping"],
    "campus": ["Architecture & Buildings"],
    "canal_natural": ["Water & Aquatic", "Natural Landscapes"],
    "canal_urban": ["Water & Aquatic", "Urban & City Scenes"],
    "candy_store": ["Markets & Commerce", "Food & Cuisine"],
    "canyon": ["Natural Landforms & Geology", "Natural Landscapes"],
    "car_interior_backseat": ["Transportation & Vehicles"],
    "car_interior_frontseat": ["Transportation & Vehicles"],
    "carrousel": ["Toys, Games & Recreation"],
    "casino_indoor": ["Toys, Games & Recreation"],
    "castle": ["Architecture & Buildings", "Historical & Antique"],
    "catacomb": ["Religious & Spiritual", "Historical & Antique"],
    "cathedral_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "cathedral_outdoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "cavern_indoor": ["Natural Landforms & Geology"],
    "cemetery": ["Religious & Spiritual"],
    "chalet": ["Architecture & Buildings", "Outdoor & Camping"],
    "cheese_factory": ["Industrial & Manufacturing", "Food & Cuisine"],
    "chemistry_lab": ["Medical & Scientific"],
    "chicken_coop_indoor": ["Animals", "Architecture & Buildings"],
    "chicken_coop_outdoor": ["Animals", "Architecture & Buildings"],
    "childs_room": ["Household Objects & Furniture", "Children & Youth"],
    "church_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "church_outdoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "classroom": ["Architecture & Buildings", "Children & Youth"],
    "clean_room": ["Industrial & Manufacturing", "Medical & Scientific"],
    "cliff": ["Natural Landforms & Geology", "Natural Landscapes"],
    "cloister_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "closet": ["Household Objects & Furniture", "Fashion & Clothing"],
    "clothing_store": ["Fashion & Clothing", "Markets & Commerce"],
    "coast": ["Water & Aquatic", "Natural Landscapes"],
    "cockpit": ["Transportation & Vehicles", "Technology & Electronics"],
    "coffee_shop": ["Food & Cuisine"],
    "computer_room": ["Technology & Electronics"],
    "conference_center": ["Architecture & Buildings"],
    "conference_room": ["Architecture & Buildings", "Office & Stationery"],
    "construction_site": ["Industrial & Manufacturing", "Urban & City Scenes"],
    "control_room": ["Technology & Electronics"],
    "control_tower_outdoor": ["Architecture & Buildings", "Transportation & Vehicles"],
    "corn_field": ["Plants & Botanical", "Natural Landscapes"],
    "corral": ["Animals", "Structures & Barriers"],
    "corridor": ["Architecture & Buildings"],
    "cottage_garden": ["Plants & Botanical"],
    "courthouse": ["Architecture & Buildings"],
    "courtroom": ["Architecture & Buildings"],
    "courtyard": ["Architecture & Buildings"],
    "covered_bridge_exterior": ["Architecture & Buildings", "Structures & Barriers"],
    "creek": ["Water & Aquatic", "Natural Landscapes"],
    "crevasse": ["Natural Landforms & Geology"],
    "crosswalk": ["Urban & City Scenes"],
    "cubicle_office": ["Office & Stationery"],
    "dam": ["Structures & Barriers", "Water & Aquatic", "Industrial & Manufacturing"],
    "delicatessen": ["Food & Cuisine", "Markets & Commerce"],
    "dentists_office": ["Medical & Scientific"],
    "desert_sand": ["Natural Landscapes", "Natural Landforms & Geology"],
    "desert_vegetation": ["Natural Landscapes", "Plants & Botanical"],
    "diner_indoor": ["Food & Cuisine"],
    "diner_outdoor": ["Food & Cuisine"],
    "dinette_home": ["Household Objects & Furniture", "Food & Cuisine"],
    "dinette_vehicle": ["Transportation & Vehicles"],
    "dining_car": ["Transportation & Vehicles", "Food & Cuisine"],
    "dining_room": ["Household Objects & Furniture", "Food & Cuisine"],
    "discotheque": ["Music, Dance & Performance"],
    "dock": ["Water & Aquatic", "Structures & Barriers"],
    "doorway_outdoor": ["Architecture & Buildings", "Structures & Barriers"],
    "dorm_room": ["Household Objects & Furniture"],
    "driveway": ["Urban & City Scenes"],
    "driving_range_outdoor": ["Sports & Athletics"],
    "drugstore": ["Markets & Commerce", "Medical & Scientific"],
    "electrical_substation": ["Industrial & Manufacturing", "Technology & Electronics"],
    "elevator_door": ["Architecture & Buildings"],
    "elevator_interior": ["Architecture & Buildings"],
    "elevator_shaft": ["Architecture & Buildings"],
    "engine_room": ["Industrial & Manufacturing", "Technology & Electronics"],
    "escalator_indoor": ["Architecture & Buildings"],
    "excavation": ["Industrial & Manufacturing"],
    "factory_indoor": ["Industrial & Manufacturing"],
    "fairway": ["Sports & Athletics"],
    "fastfood_restaurant": ["Food & Cuisine"],
    "field_cultivated": ["Plants & Botanical", "Natural Landscapes"],
    "field_wild": ["Natural Landscapes", "Plants & Botanical"],
    "fire_escape": ["Architecture & Buildings", "Structures & Barriers"],
    "fire_station": ["Architecture & Buildings"],
    "firing_range_indoor": ["Sports & Athletics", "Weapons & Armor"],
    "fishpond": ["Water & Aquatic"],
    "florist_shop_indoor": ["Plants & Botanical", "Markets & Commerce"],
    "food_court": ["Food & Cuisine"],
    "forest_broadleaf": ["Trees & Forests"],
    "forest_needleleaf": ["Trees & Forests"],
    "forest_path": ["Trees & Forests"],
    "forest_road": ["Trees & Forests"],
    "formal_garden": ["Plants & Botanical"],
    "fountain": ["Water & Aquatic"],
    "galley": ["Kitchen & Cooking Equipment", "Transportation & Vehicles"],
    "game_room": ["Toys, Games & Recreation"],
    "garage_indoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "garbage_dump": ["Industrial & Manufacturing"],
    "gas_station": ["Transportation & Vehicles", "Urban & City Scenes"],
    "gazebo_exterior": ["Architecture & Buildings", "Structures & Barriers"],
    "general_store_indoor": ["Markets & Commerce"],
    "general_store_outdoor": ["Markets & Commerce"],
    "gift_shop": ["Markets & Commerce"],
    "golf_course": ["Sports & Athletics"],
    "greenhouse_indoor": ["Plants & Botanical"],
    "greenhouse_outdoor": ["Plants & Botanical"],
    "gymnasium_indoor": ["Sports & Athletics"],
    "hangar_indoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "hangar_outdoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "harbor": ["Water & Aquatic", "Transportation & Vehicles"],
    "hayfield": ["Plants & Botanical", "Natural Landscapes"],
    "heliport": ["Transportation & Vehicles"],
    "herb_garden": ["Plants & Botanical"],
    "highway": ["Transportation & Vehicles", "Urban & City Scenes"],
    "hill": ["Natural Landscapes", "Natural Landforms & Geology"],
    "home_office": ["Office & Stationery", "Household Objects & Furniture"],
    "hospital": ["Medical & Scientific", "Architecture & Buildings"],
    "hospital_room": ["Medical & Scientific"],
    "hot_spring": ["Water & Aquatic", "Natural Landscapes"],
    "hot_tub_outdoor": ["Water & Aquatic"],
    "hotel_outdoor": ["Architecture & Buildings"],
    "hotel_room": ["Household Objects & Furniture"],
    "house": ["Architecture & Buildings"],
    "hunting_lodge_outdoor": ["Architecture & Buildings", "Outdoor & Camping"],
    "ice_cream_parlor": ["Food & Cuisine", "Markets & Commerce"],
    "ice_floe": ["Water & Aquatic", "Natural Landscapes", "Weather & Atmosphere"],
    "ice_shelf": ["Water & Aquatic", "Natural Landscapes"],
    "ice_skating_rink_indoor": ["Sports & Athletics"],
    "ice_skating_rink_outdoor": ["Sports & Athletics"],
    "iceberg": ["Water & Aquatic", "Natural Landforms & Geology"],
    "igloo": ["Architecture & Buildings", "Cultural & Traditional"],
    "industrial_area": ["Industrial & Manufacturing", "Urban & City Scenes"],
    "inn_outdoor": ["Architecture & Buildings"],
    "islet": ["Water & Aquatic", "Natural Landscapes"],
    "jacuzzi_indoor": ["Water & Aquatic"],
    "jail_cell": ["Structures & Barriers"],
    "jail_indoor": ["Structures & Barriers"],
    "jewelry_shop": ["Jewelry & Accessories", "Markets & Commerce"],
    "kasbah": ["Architecture & Buildings", "Cultural & Traditional", "Historical & Antique"],
    "kennel_indoor": ["Dogs & Canines", "Animals"],
    "kennel_outdoor": ["Dogs & Canines", "Animals"],
    "kindergarden_classroom": ["Children & Youth", "Architecture & Buildings"],
    "kitchen": ["Kitchen & Cooking Equipment", "Household Objects & Furniture"],
    "kitchenette": ["Kitchen & Cooking Equipment"],
    "labyrinth_outdoor": ["Plants & Botanical", "Structures & Barriers"],
    "lake_natural": ["Water & Aquatic", "Natural Landscapes"],
    "landfill": ["Industrial & Manufacturing"],
    "landing_deck": ["Transportation & Vehicles"],
    "laundromat": ["Markets & Commerce"],
    "lecture_room": ["Architecture & Buildings", "Children & Youth"],
    "library_indoor": ["Letters, Text & Writing", "Architecture & Buildings"],
    "library_outdoor": ["Architecture & Buildings", "Historical & Antique"],
    "lido_deck_outdoor": ["Transportation & Vehicles", "Water & Aquatic"],
    "lift_bridge": ["Architecture & Buildings", "Structures & Barriers"],
    "lighthouse": ["Architecture & Buildings", "Water & Aquatic"],
    "limousine_interior": ["Transportation & Vehicles"],
    "living_room": ["Household Objects & Furniture"],
    "lobby": ["Architecture & Buildings"],
    "lock_chamber": ["Water & Aquatic", "Structures & Barriers"],
    "locker_room": ["Sports & Athletics"],
    "mansion": ["Architecture & Buildings"],
    "manufactured_home": ["Architecture & Buildings"],
    "market_indoor": ["Markets & Commerce"],
    "market_outdoor": ["Markets & Commerce"],
    "marsh": ["Water & Aquatic", "Natural Landscapes"],
    "martial_arts_gym": ["Sports & Athletics"],
    "mausoleum": ["Religious & Spiritual", "Historical & Antique"],
    "medina": ["Architecture & Buildings", "Cultural & Traditional", "Urban & City Scenes"],
    "moat_water": ["Water & Aquatic", "Structures & Barriers"],
    "monastery_outdoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "mosque_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "mosque_outdoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "motel": ["Architecture & Buildings"],
    "mountain": ["Natural Landscapes", "Natural Landforms & Geology"],
    "mountain_snowy": ["Natural Landscapes", "Natural Landforms & Geology", "Weather & Atmosphere"],
    "movie_theater_indoor": ["Music, Dance & Performance", "Architecture & Buildings"],
    "museum_indoor": ["Architecture & Buildings", "Historical & Antique"],
    "music_store": ["Markets & Commerce", "Musical Instruments"],
    "music_studio": ["Music, Dance & Performance", "Musical Instruments"],
    "nuclear_power_plant_outdoor": ["Industrial & Manufacturing"],
    "nursery": ["Children & Youth", "Household Objects & Furniture"],
    "oast_house": ["Architecture & Buildings", "Industrial & Manufacturing"],
    "observatory_outdoor": ["Architecture & Buildings", "Sky & Space", "Optical & Scientific Instruments"],
    "ocean": ["Water & Aquatic", "Natural Landscapes"],
    "office": ["Office & Stationery"],
    "office_building": ["Architecture & Buildings", "Urban & City Scenes"],
    "oil_refinery_outdoor": ["Industrial & Manufacturing"],
    "oilrig": ["Industrial & Manufacturing", "Water & Aquatic"],
    "operating_room": ["Medical & Scientific"],
    "orchard": ["Plants & Botanical", "Trees & Forests", "Fruits"],
    "outhouse_outdoor": ["Architecture & Buildings"],
    "pagoda": ["Architecture & Buildings", "Religious & Spiritual", "Cultural & Traditional"],
    "palace": ["Architecture & Buildings", "Historical & Antique"],
    "pantry": ["Kitchen & Cooking Equipment", "Food & Cuisine"],
    "park": ["Natural Landscapes", "Plants & Botanical"],
    "parking_garage_indoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "parking_garage_outdoor": ["Transportation & Vehicles", "Architecture & Buildings"],
    "parking_lot": ["Transportation & Vehicles", "Urban & City Scenes"],
    "parlor": ["Household Objects & Furniture"],
    "pasture": ["Animals", "Natural Landscapes"],
    "patio": ["Architecture & Buildings", "Household Objects & Furniture"],
    "pavilion": ["Architecture & Buildings", "Structures & Barriers"],
    "pharmacy": ["Medical & Scientific", "Markets & Commerce"],
    "phone_booth": ["Technology & Electronics", "Structures & Barriers"],
    "physics_laboratory": ["Medical & Scientific"],
    "picnic_area": ["Outdoor & Camping"],
    "pilothouse_indoor": ["Transportation & Vehicles"],
    "planetarium_outdoor": ["Architecture & Buildings", "Sky & Space"],
    "playground": ["Toys, Games & Recreation", "Children & Youth"],
    "playroom": ["Toys, Games & Recreation", "Children & Youth"],
    "plaza": ["Urban & City Scenes"],
    "podium_indoor": ["Music, Dance & Performance"],
    "podium_outdoor": ["Music, Dance & Performance"],
    "pond": ["Water & Aquatic", "Natural Landscapes"],
    "poolroom_establishment": ["Sports & Athletics", "Toys, Games & Recreation"],
    "poolroom_home": ["Toys, Games & Recreation"],
    "power_plant_outdoor": ["Industrial & Manufacturing"],
    "promenade_deck": ["Transportation & Vehicles", "Water & Aquatic"],
    "pub_indoor": ["Food & Cuisine"],
    "pulpit": ["Religious & Spiritual"],
    "putting_green": ["Sports & Athletics"],
    "racecourse": ["Sports & Athletics"],
    "raceway": ["Sports & Athletics", "Transportation & Vehicles"],
    "raft": ["Water & Aquatic", "Transportation & Vehicles"],
    "railroad_track": ["Transportation & Vehicles", "Structures & Barriers"],
    "rainforest": ["Trees & Forests", "Natural Landscapes"],
    "reception": ["Architecture & Buildings", "Office & Stationery"],
    "recreation_room": ["Toys, Games & Recreation"],
    "residential_neighborhood": ["Urban & City Scenes", "Architecture & Buildings"],
    "restaurant": ["Food & Cuisine"],
    "restaurant_kitchen": ["Kitchen & Cooking Equipment", "Food & Cuisine"],
    "restaurant_patio": ["Food & Cuisine"],
    "rice_paddy": ["Plants & Botanical", "Natural Landscapes", "Water & Aquatic"],
    "riding_arena": ["Sports & Athletics", "Animals"],
    "river": ["Water & Aquatic", "Natural Landscapes"],
    "rock_arch": ["Natural Landforms & Geology", "Natural Landscapes"],
    "rope_bridge": ["Structures & Barriers"],
    "ruin": ["Historical & Antique", "Architecture & Buildings"],
    "runway": ["Transportation & Vehicles"],
    "sandbar": ["Water & Aquatic", "Natural Landscapes"],
    "sandbox": ["Toys, Games & Recreation", "Children & Youth"],
    "sauna": ["Architecture & Buildings"],
    "schoolhouse": ["Architecture & Buildings", "Children & Youth"],
    "sea_cliff": ["Natural Landforms & Geology", "Water & Aquatic", "Natural Landscapes"],
    "server_room": ["Technology & Electronics"],
    "shed": ["Architecture & Buildings"],
    "shoe_shop": ["Footwear", "Markets & Commerce"],
    "shopfront": ["Markets & Commerce", "Architecture & Buildings"],
    "shopping_mall_indoor": ["Markets & Commerce", "Architecture & Buildings"],
    "shower": ["Household Objects & Furniture", "Water & Aquatic"],
    "skatepark": ["Sports & Athletics"],
    "ski_lodge": ["Architecture & Buildings", "Sports & Athletics"],
    "ski_resort": ["Sports & Athletics", "Natural Landscapes"],
    "ski_slope": ["Sports & Athletics", "Natural Landscapes"],
    "sky": ["Sky & Space", "Weather & Atmosphere"],
    "skyscraper": ["Architecture & Buildings", "Urban & City Scenes"],
    "slum": ["Urban & City Scenes"],
    "snowfield": ["Natural Landscapes", "Weather & Atmosphere"],
    "squash_court": ["Sports & Athletics"],
    "stable": ["Animals", "Architecture & Buildings"],
    "stadium_baseball": ["Sports & Athletics"],
    "stadium_football": ["Sports & Athletics"],
    "stage_indoor": ["Music, Dance & Performance"],
    "staircase": ["Architecture & Buildings"],
    "street": ["Urban & City Scenes"],
    "subway_interior": ["Transportation & Vehicles"],
    "subway_station_platform": ["Transportation & Vehicles", "Urban & City Scenes"],
    "supermarket": ["Markets & Commerce", "Food & Cuisine"],
    "sushi_bar": ["Food & Cuisine"],
    "swamp": ["Water & Aquatic", "Natural Landscapes"],
    "swimming_pool_indoor": ["Water & Aquatic", "Sports & Athletics"],
    "swimming_pool_outdoor": ["Water & Aquatic", "Sports & Athletics"],
    "synagogue_indoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "synagogue_outdoor": ["Architecture & Buildings", "Religious & Spiritual"],
    "television_studio": ["Music, Dance & Performance", "Technology & Electronics"],
    "temple_east_asia": ["Architecture & Buildings", "Religious & Spiritual", "Cultural & Traditional"],
    "temple_south_asia": ["Architecture & Buildings", "Religious & Spiritual", "Cultural & Traditional"],
    "tennis_court_indoor": ["Sports & Athletics"],
    "tennis_court_outdoor": ["Sports & Athletics"],
    "tent_outdoor": ["Outdoor & Camping"],
    "theater_indoor_procenium": ["Music, Dance & Performance", "Architecture & Buildings"],
    "theater_indoor_seats": ["Music, Dance & Performance", "Architecture & Buildings"],
    "thriftshop": ["Markets & Commerce"],
    "throne_room": ["Historical & Antique", "Architecture & Buildings"],
    "ticket_booth": ["Markets & Commerce", "Structures & Barriers"],
    "toll_plaza": ["Transportation & Vehicles"],
    "topiary_garden": ["Plants & Botanical"],
    "tower": ["Architecture & Buildings", "Structures & Barriers"],
    "toyshop": ["Toys, Games & Recreation", "Markets & Commerce"],
    "track_outdoor": ["Sports & Athletics"],
    "train_railway": ["Transportation & Vehicles"],
    "train_station_platform": ["Transportation & Vehicles", "Urban & City Scenes"],
    "tree_farm": ["Trees & Forests", "Plants & Botanical"],
    "tree_house": ["Architecture & Buildings", "Trees & Forests"],
    "trench": ["Structures & Barriers", "Natural Landforms & Geology"],
    "underwater_coral_reef": ["Marine & Aquatic Life", "Water & Aquatic"],
    "utility_room": ["Household Objects & Furniture"],
    "valley": ["Natural Landscapes", "Natural Landforms & Geology"],
    "van_interior": ["Transportation & Vehicles"],
    "vegetable_garden": ["Vegetables & Produce", "Plants & Botanical"],
    "veranda": ["Architecture & Buildings"],
    "veterinarians_office": ["Medical & Scientific", "Animals"],
    "viaduct": ["Architecture & Buildings", "Structures & Barriers"],
    "videostore": ["Markets & Commerce"],
    "village": ["Urban & City Scenes", "Architecture & Buildings"],
    "vineyard": ["Plants & Botanical", "Fruits", "Natural Landscapes"],
    "volcano": ["Fire, Smoke & Volcanic", "Natural Landforms & Geology"],
    "volleyball_court_indoor": ["Sports & Athletics"],
    "volleyball_court_outdoor": ["Sports & Athletics"],
    "waiting_room": ["Architecture & Buildings", "Household Objects & Furniture"],
    "warehouse_indoor": ["Industrial & Manufacturing", "Architecture & Buildings"],
    "water_tower": ["Structures & Barriers", "Water & Aquatic"],
    "waterfall_block": ["Water & Aquatic", "Natural Landscapes"],
    "waterfall_fan": ["Water & Aquatic", "Natural Landscapes"],
    "waterfall_plunge": ["Water & Aquatic", "Natural Landscapes"],
    "watering_hole": ["Water & Aquatic", "Animals"],
    "wave": ["Water & Aquatic"],
    "wet_bar": ["Food & Cuisine", "Household Objects & Furniture"],
    "wheat_field": ["Plants & Botanical", "Natural Landscapes"],
    "wind_farm": ["Industrial & Manufacturing", "Technology & Electronics"],
    "windmill": ["Architecture & Buildings", "Industrial & Manufacturing"],
    "wine_cellar_barrel_storage": ["Food & Cuisine"],
    "wine_cellar_bottle_storage": ["Food & Cuisine"],
    "wrestling_ring_indoor": ["Sports & Athletics"],
    "yard": ["Household Objects & Furniture", "Outdoor & Camping"],
    "youth_hostel": ["Architecture & Buildings", "Children & Youth"],
}

# Load classes.txt to confirm full set
with open("/home/nfm/Desktop/rhome/nfm/sun_dataset_folder_sampled/classes.txt") as f:
    all_classes = [line.strip() for line in f if line.strip()]

# Load json
with open(JSON_PATH) as f:
    data = json.load(f)

group_keys = set(data["groups"].keys())

# Validate all target groups exist
bad = set()
for cls, groups in mapping.items():
    for g in groups:
        if g not in group_keys:
            bad.add(g)
if bad:
    raise SystemExit(f"Unknown group names referenced: {bad}")

# Invert: group -> classes (preserve classes.txt order)
group_to_classes = {g: [] for g in data["groups"]}
classified = set()
for cls in all_classes:
    groups = mapping.get(cls, [])
    if groups:
        classified.add(cls)
    for g in groups:
        group_to_classes[g].append(cls)

# Append to imagenet_classes (avoid duplicates already present)
for g, classes in group_to_classes.items():
    existing = data["groups"][g].setdefault("imagenet_classes", [])
    existing_set = set(existing)
    for c in classes:
        if c not in existing_set:
            existing.append(c)
            existing_set.add(c)

with open(JSON_PATH, "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

total = len(all_classes)
done = len(classified)
unclassified = [c for c in all_classes if c not in classified]
print(f"Total classes: {total}")
print(f"Classified:    {done} ({100.0*done/total:.1f}%)")
print(f"Unclassified:  {len(unclassified)} ({100.0*len(unclassified)/total:.1f}%)")
if unclassified:
    print("Unclassified list:", unclassified)
